// Clean Production Data Configuration for Maa Durga Engineering - VST Zetor Tractor Dealership OS
// Verified VST ZETOR technical lineup (4211, 4511, 5011 in 2WD and 4WD configurations)

export const SHOWROOM_INFO = {
  name: "Maa Durga Engineering",
  tagline: "Authorized VST Zetor Agricultural Machinery & Tractor Sales, Service & Spares Dealership",
  address: "NH-28 Bypass Road, Near Kisan Mandi, Industrial Area, Gorakhpur - 273001, UP",
  phone: "+91 98380 12345",
  whatsapp: "919838012345",
  email: "sales@maadurgaengineering.in",
  gstin: "09AAACM4521K1ZF",
  bankName: "State Bank of India",
  accountNo: "3892010482910",
  ifsc: "SBIN0001248",
  authorizedBrands: ["VST Zetor", "VST Tillers Tractors", "Zetor"]
};

// Standard Tractor Technical Catalog (VST ZETOR Lineup)
export const DEFAULT_TRACTORS = [
  {
    id: "TRAC-001",
    brand: "VST Zetor",
    model: "4211 2WD",
    hp: 42,
    ptoHp: 38,
    engineCc: 2500,
    cylinders: 3,
    liftCapacityKg: 1800,
    transmission: "Fully Constant Mesh Helical (8 F + 2 R)",
    drive: "2WD",
    price: 745000,
    dealerPurchaseCost: 670000,
    stockCount: 0,
    bestSoil: ["All Types", "Sandy Loam", "Medium", "Loam"],
    recommendedAcresMin: 5,
    recommendedAcresMax: 18,
    compatibleImplements: ["Rotavator (5 ft)", "Cultivator (9 Tyne)", "Trolley (6-8 Ton)", "Thresher", "Sprayer"],
    popularCrops: ["Wheat", "Mustard", "Vegetables", "Paddy", "Pulses"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  },
  {
    id: "TRAC-002",
    brand: "VST Zetor",
    model: "4211 4WD",
    hp: 42,
    ptoHp: 38,
    engineCc: 2500,
    cylinders: 3,
    liftCapacityKg: 1800,
    transmission: "Fully Constant Mesh Helical (8 F + 2 R)",
    drive: "4WD",
    price: 795000,
    dealerPurchaseCost: 715000,
    stockCount: 0,
    bestSoil: ["Wetland / Puddle", "Clay", "Black Soil", "Loam"],
    recommendedAcresMin: 6,
    recommendedAcresMax: 22,
    compatibleImplements: ["Rotavator (5-6 ft)", "Puddler", "Cultivator (9 Tyne)", "Trolley (8 Ton)"],
    popularCrops: ["Paddy / Rice", "Wheat", "Potato", "Sugarcane"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  },
  {
    id: "TRAC-003",
    brand: "VST Zetor",
    model: "4511 2WD",
    hp: 47,
    ptoHp: 40.5,
    engineCc: 2979,
    cylinders: 3,
    liftCapacityKg: 1800,
    transmission: "Fully Constant Mesh Helical (8 F + 2 R) Side Shift",
    drive: "2WD",
    price: 770000,
    dealerPurchaseCost: 695000,
    stockCount: 0,
    bestSoil: ["Medium", "Loam", "Clay Loam", "All Types"],
    recommendedAcresMin: 8,
    recommendedAcresMax: 28,
    compatibleImplements: ["Rotavator (6 ft)", "Cultivator (11 Tyne)", "Trolley (8-10 Ton)", "MB Plough (2 Bottom)", "Thresher"],
    popularCrops: ["Wheat", "Paddy", "Sugarcane", "Potato", "Maize"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  },
  {
    id: "TRAC-004",
    brand: "VST Zetor",
    model: "4511 4WD",
    hp: 47,
    ptoHp: 40.5,
    engineCc: 2979,
    cylinders: 3,
    liftCapacityKg: 1800,
    transmission: "Fully Constant Mesh Helical (8 F + 2 R)",
    drive: "4WD",
    price: 835000,
    dealerPurchaseCost: 750000,
    stockCount: 0,
    bestSoil: ["Heavy Black", "Clay", "Wet Puddling", "Loam"],
    recommendedAcresMin: 10,
    recommendedAcresMax: 35,
    compatibleImplements: ["Heavy Rotavator (6 ft)", "Laser Leveller", "Puddler", "MB Plough", "Heavy Trolley (10 Ton)"],
    popularCrops: ["Sugarcane", "Paddy", "Wheat", "Cotton", "Potato"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  },
  {
    id: "TRAC-005",
    brand: "VST Zetor",
    model: "5011 2WD",
    hp: 50,
    ptoHp: 43.5,
    engineCc: 3220,
    cylinders: 3,
    liftCapacityKg: 2000,
    transmission: "Helical Constant Mesh (8 F + 2 R / Dual Clutch)",
    drive: "2WD",
    price: 820000,
    dealerPurchaseCost: 740000,
    stockCount: 0,
    bestSoil: ["Heavy Black", "Hard Soil", "Loam", "Medium"],
    recommendedAcresMin: 12,
    recommendedAcresMax: 45,
    compatibleImplements: ["Rotavator (6-7 ft)", "Cultivator (11-13 Tyne)", "MB Plough (2 Bottom Heavy)", "Trolley (10-12 Ton)", "Laser Leveller"],
    popularCrops: ["Sugarcane", "Wheat", "Paddy", "Cotton", "Potato"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  },
  {
    id: "TRAC-006",
    brand: "VST Zetor",
    model: "5011 4WD",
    hp: 50,
    ptoHp: 43.8,
    engineCc: 3220,
    cylinders: 3,
    liftCapacityKg: 2000,
    transmission: "Helical Constant Mesh (8 F + 2 R / 16 F + 4 R Option)",
    drive: "4WD",
    price: 885000,
    dealerPurchaseCost: 798000,
    stockCount: 0,
    bestSoil: ["Heavy Black Soil", "Deep Clay", "Challenging Terrains", "Wet Puddling"],
    recommendedAcresMin: 15,
    recommendedAcresMax: 55,
    compatibleImplements: ["Heavy Rotavator (7 ft)", "Square Baler", "Heavy MB Plough (3 Bottom)", "Laser Leveller", "Heavy Haulage Trolley (12-14 Ton)"],
    popularCrops: ["Sugarcane", "Wheat", "Paddy", "Cotton", "Commercial Haulage"],
    chassisList: [],
    warranty: "6 Years / 6000 Hours Warranty",
    status: "Available to Order"
  }
];

// Production Clean Slate - Zero Seed Data
export const DEFAULT_LEADS = [];
export const DEFAULT_EXPENSES = [];
export const DEFAULT_CASH_TRANSACTIONS = [];
export const DEFAULT_DEMOS = [];
export const DEFAULT_QUOTES = [];

export const DEFAULT_BILLS = [];
